#  Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

import os
import boto3
import json
import botocore
import base64
import io
from utils.rekognition import RekognitionImage
from utils.rekognition import RekognitionLabel
from utils.rekognition import RekognitionText
from customLogging.logger import safeLogger
import manifestHelper
from botocore.config import Config

# Adaptive retry with client-side rate limiting, per backendPipelines/CLAUDE.md. A pipeline lambda
# runs against throttling-prone services (Step Functions, Amazon S3, EventBridge) for the length of
# a job, so a bare client leaves it on botocore's default mode with no rate limiting and a sustained
# burst surfaces as a throttling error on the caller instead of being smoothed.
retry_config = Config(retries={'max_attempts': 5, 'mode': 'adaptive'})

logger = safeLogger(service="MetadataGenerationPipeline")

s3_client = boto3.client('s3', config=retry_config)
s3_resource = boto3.resource('s3', config=retry_config)
rekognition_client = boto3.client('rekognition', config=retry_config)
bedrock_client = boto3.client('bedrock-runtime', config=retry_config)
max_tokens = 10000
metadataJsonPrimaryKey = "autoGeneratedKeywords"
metadataFileObjectName = "asset.metadata.json"


class ModelResponseError(Exception):
    """A model response that carries no usable text content."""

# Load environment variables
try:
    model_id = os.environ["BEDROCK_MODEL_ID"]
except Exception as e:
    logger.exception("Failed loading environment variables")
    raise e

def image_to_base64(img_path) -> str:
    with open(img_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

def get_all_image_files_in_path(bucket, path):

    result = {
        "Items": []
    }

    # Paginate: a single page caps at 1,000 keys, so a render set larger than that
    # would be only partially labeled.
    paginator = s3_client.get_paginator('list_objects_v2')
    for page in paginator.paginate(Bucket=bucket, Prefix=path):
        # map object from object list
        for o in page.get("Contents", []):
            if o['Key'].endswith('.png'):
                result["Items"].append({
                    'key': o['Key'],
                    'relativePath': o['Key'].removeprefix(path)
                })

    # Log the length of files with a description
    logger.info("Files in the path: ")
    logger.info(len(result["Items"]))
    return result["Items"]


def invoke_claude_3_with_text(prompt, base64_image_data = None):
    """
    Invokes Anthropic Claude 3 Sonnet to run an inference using the input
    provided in the request body.

    :param prompt: The prompt that you want Claude 3 to complete along with the image.
    :return: Inference response from the model.
    """


    body = ""
    if base64_image_data:
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": max_tokens,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        },
                        {
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": "image/png",
                                "data": base64_image_data,
                            },
                        },
                        ],
                }
            ],
        }
    else:
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": max_tokens,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                        ],
                }
            ],
        }

    try:
        response = bedrock_client.invoke_model(
            modelId=model_id,
            body=json.dumps(body),
        )

        # Process and print the response
        result = json.loads(response.get("body").read())
        if not isinstance(result, dict):
            raise ModelResponseError(
                f"Model response is not a JSON object (got {type(result).__name__})."
            )

        usage = result.get("usage", {})
        output_list = result.get("content", [])

        logger.info("Invocation details:")
        logger.info(f"- The input length is {usage.get('input_tokens')} tokens.")
        logger.info(f"- The output length is {usage.get('output_tokens')} tokens.")

        logger.info(f"- The model returned {len(output_list)} response(s):")
        for output in output_list:
            logger.info(output.get("text") if isinstance(output, dict) else output)

        return result

    except botocore.exceptions.ClientError as err:
        logger.exception("Couldn't invoke Bedrock LLM.")
        logger.exception(err)
        raise


def extract_model_text(claude_result) -> str:
    """
    Read the text of the model response's first content block.

    :param claude_result: Parsed response body from invoke_claude_3_with_text.
    :return: The text of the first content block.
    :raises ModelResponseError: With a shape-specific message, so a model that legitimately
        returned no content blocks is distinguishable from a malformed response.
    """
    if not isinstance(claude_result, dict):
        raise ModelResponseError(
            f"Model response is not a JSON object (got {type(claude_result).__name__})."
        )

    if "content" not in claude_result:
        raise ModelResponseError("Model response carries no 'content' field.")

    content = claude_result["content"]
    if not isinstance(content, list):
        raise ModelResponseError(
            f"Model response 'content' is not a list (got {type(content).__name__})."
        )

    if len(content) == 0:
        raise ModelResponseError("Model response returned an empty 'content' list.")

    block = content[0]
    if not isinstance(block, dict) or not isinstance(block.get("text"), str):
        raise ModelResponseError("Model response content block carries no 'text' string.")

    return block["text"]


def metadata_dict_to_str_array(metadata_dict):
    """
    Convert simplified metadata dictionary to string array for aggregation.
    
    Args:
        metadata_dict: Dictionary with key-value pairs (simplified format from executeWorkflow)
        
    Returns:
        Array of strings in format "key:::value"
    """
    arr = []
    for key, value in metadata_dict.items():
        # Skip the auto-generated keywords field to avoid recursion
        if key == metadataJsonPrimaryKey:
            continue
        
        if value and str(value) != "":
            arr.append(f"{key}:::{value}")
    
    return arr


def aggregate_input_metadata_fields(metadata_body):
    """Flatten every metadata scope of the run metadata payload into the "key:::value" seed list.

    The metadata file is the grouped-by-asset envelope: each asset group contributes its
    asset-level metadata (the fileKey '/' record) plus each file record's metadata and
    attributes. A legacy ``{"VAMS": {...}}`` body reads its three scopes directly, so both
    payload shapes seed the prompt with the same elements.
    """
    fields = []
    if not isinstance(metadata_body, dict):
        return fields

    if "assets" in metadata_body:
        for asset_group in metadata_body.get("assets") or []:
            database_id = asset_group.get("databaseId", "")
            asset_id = asset_group.get("assetId", "")
            fields.extend(metadata_dict_to_str_array(
                manifestHelper.asset_metadata_for(metadata_body, database_id, asset_id)))
            for file_record in asset_group.get("files") or []:
                file_key = file_record.get("fileKey", "")
                if file_key in ("", "/"):
                    continue
                fields.extend(metadata_dict_to_str_array(
                    manifestHelper.file_metadata_for(metadata_body, database_id, asset_id, file_key)))
                fields.extend(metadata_dict_to_str_array(
                    manifestHelper.file_attributes_for(metadata_body, database_id, asset_id, file_key)))
        return fields

    vams_metadata = metadata_body.get("VAMS", {}) or {}
    fields.extend(metadata_dict_to_str_array(vams_metadata.get("assetMetadata") or {}))
    fields.extend(metadata_dict_to_str_array(vams_metadata.get("fileMetadata") or {}))
    fields.extend(metadata_dict_to_str_array(vams_metadata.get("fileAttributes") or {}))
    return fields


def lambda_handler(event, context):
    """
    Metadata Generation Pipeline Lambda Handler
    Handle processing of GenAI metadata labeling, metadata saving, and cleanup
    """

    logger.info(f"Event Input: {event}")
    logger.info(f"Context Input: {context}")

    #TODO: Try/catch

    pipelineDefinitions = json.loads(event['definition'][0])
    pipelineStageDefinition = {}

    #TODO: use container code as a layer to provide better definition ingestion / responsing
    foundStage = False
    for stage in pipelineDefinitions['stages']:
        if stage['type'] == 'METADATAGENERATION':
            pipelineStageDefinition = stage
            foundStage = True
            break

    if foundStage == False:
        logger.error("No metadata generation stage found in pipeline definition.")
        raise Exception("No metadata generation stage found in pipeline definition.")
    
    #Read input configuration + metadata from S3 (only the locations travel in the definition)
    inputConfigurationS3Location = pipelineDefinitions.get("inputConfigurationS3Location", "")
    inputMetadataS3Location = pipelineDefinitions.get("inputMetadataS3Location", "")

    inputParametersObject = manifestHelper.fetch_input_configuration(s3_client, inputConfigurationS3Location)
    if not inputParametersObject:
        #Transition fallback for legacy payloads that still forward inline content
        inlineParameters = event.get("inputParameters", "")
        if(isinstance(inlineParameters,str) and inlineParameters != ""):
            try:
                inputParametersObject = json.loads(inlineParameters)
            except:
                logger.error("Input parameters is not valid JSON.")

    inputMetadataObject = manifestHelper.fetch_metadata(s3_client, inputMetadataS3Location)
    if not inputMetadataObject:
        #Transition fallback for legacy payloads that still forward inline content
        inlineMetadata = event.get("inputMetadata", "")
        if(isinstance(inlineMetadata,str) and inlineMetadata != ""):
            try:
                inputMetadataObject = json.loads(inlineMetadata)
            except:
                logger.error("Input metadata is not valid JSON.")

    #Get input/output locations
    inputBucket = pipelineStageDefinition['inputFile']['bucketName']
    inputKeyDir = pipelineStageDefinition['inputFile']['objectDir']
    outputTempBucket = pipelineStageDefinition['temporaryFiles']['bucketName']
    outputTempKeyDir = pipelineStageDefinition['temporaryFiles']['objectDir']
    outputMetadataBucket = pipelineStageDefinition['outputMetadata'].get("bucketName", "")
    outputMetadataKeyDir = pipelineStageDefinition['outputMetadata'].get("objectDir", "")

    #Get input parameters
    seedMetadataGenerationWithInputMetadata = inputParametersObject.get("seedMetadataGenerationWithInputMetadata", "False")

    #Input Metadata Fields to Aggregate for use from Various Called Systems
    inputMetadataFieldsToAggregate = []
    if seedMetadataGenerationWithInputMetadata == "True":
        # Aggregate every metadata scope of the run metadata payload into the prompt seed list
        inputMetadataFieldsToAggregate = aggregate_input_metadata_fields(inputMetadataObject)


    #Get all S3 image paths at input bucket directory location
    imagePaths = get_all_image_files_in_path(bucket=inputBucket, path=inputKeyDir)

    #Error if no images returned
    if len(imagePaths) == 0:
        logger.error("No images found in the input directory.")
        raise Exception("No images found in the input directory.")

    #Prompt text
    promptImage = "You are given an image of a single camera view from a set of rendered images of a 3D object. \
        Describe to me the scene and objects in the image with only a comma-deliminated set of labels that match a confidence score of 97% or greater. \
        If the image provided is blank, has no objects in it besides a basic background color, has objects that are too small, has a bad camera angle of the object, or has unreconigzable objects, then return the single keyword of 'none'. \
        Error on the side of high confidence when choosing labels as multiple images will be evaluated and the aggregate of the labels will be used. "
    
    if len(inputMetadataFieldsToAggregate) > 0:
        logger.info("Input Metadata Fields Used: "+str(';'.join(inputMetadataFieldsToAggregate)))
        promptImage = promptImage + f"Use the provided semicolon-deliminated key-value metadata elements to help further curate the labels identified from the rendered image and reduce outliers. \
          These provided metadata elements are pre-associations that users have saved in the system with the 3D object. \
          Each provided key-value pair elements will be in the form of 'key:::value'. \
          The metadata elements are: '''{';'.join(inputMetadataFieldsToAggregate)}'''"

    promptImage = promptImage + ". Again, Skip the preamble and ONLY return the list of comma deliminated labels or 'none'"

    returnText = ""

    # Path to store images files in temporary storage
    logger.info("S3 Image paths to process:")
    for imagePath in imagePaths:
        logger.info(imagePath)
        tmp_image_path = '/tmp/' + imagePath['relativePath']
        s3_client.download_file(inputBucket, imagePath['key'], tmp_image_path) 
        image_base64 = image_to_base64(tmp_image_path)

        #Call claude
        try:
            claude_result = invoke_claude_3_with_text(promptImage, image_base64)
            claudResultText = extract_model_text(claude_result)
        except ModelResponseError as e:
            #The remaining images and Rekognition still contribute labels for this run
            logger.warning(f"No model labels for image {imagePath['key']}: {e}")
            claudResultText = "none"

        if claudResultText != "none":
            returnText = returnText + claudResultText + "," 
            logger.info("Claude Returned Keywords: "+claudResultText)
        else:
            logger.info("Claude Returned Keywords: none")

        #Call rekognition
        rekognition_image = RekognitionImage.from_file(
            tmp_image_path, rekognition_client
        )

        #get labels
        labels = rekognition_image.detect_labels(30)
        logger.info(f"Found {len(labels)} labels by rekognition total (all confidences).")
        for label in labels:
            try:
                if float(label.confidence) > 97:
                    logger.info("Label found within confidence:" + label.name)
                    returnText = returnText + label.name + ","
            except Exception as e:
                logger.info("Rekognition Error. Could not parse label.")

        #todo: get text from images too?
        
        #Remove tempoary images
        if os.path.exists(tmp_image_path):
            os.remove(tmp_image_path)

    #Final claude summary
    promptFinalSummarization = "Task: Consolidate a list of image labels into a JSON object with the following criteria: \
                                Deduplication: Remove duplicate keywords, regardless of case. (e.g., 'Red Car' and 'red car' should be treated as the same). \
                                Outlier Analysis: Identify and remove keywords that appear infrequently compared to the overall set. You can implement a threshold filter and do sentiment analysis. For example, remove keywords that appear less than 10% of the time. (This threshold can be adjusted based on the expected data distribution).\
                                Casing: Convert all keywords to lowercase unless it is a acronym like 'CAD'. \
                                Seed Metadata Integration: (Optional) If provided, use a separate list of seed keywords, phrases, or descriptions as metadata to help refine the final list of image label keywords. These seed keywords could describe the overall theme or category of the image collection. Do not automatically add these seed keywords to the final output. Only keywords that appear in the image label inputs should be the set used for the output. \
                                ONLY output at the end the final JSON object with no other preamble or explanation.\
                                Inputs:\
                                image_labels: A list of strings representing the labels assigned to each image.\
                                seed_keywords (Optional): A list of strings representing additional metadata keywords describing the image collection.\
                                Output:\
                                A JSON object with a single key '"+metadataJsonPrimaryKey+"' containing a list of filtered and deduplicated string keywords.\
                                DO NOT OUTPUT ANYTHING BUT JSON, DO NOT WRAP THE OUTPUT IN ANY ```json``` tags. \
                                Example Input/Output:\
                                example_image_labels = ['red car', 'blue car', 'red truck', 'tree', 'Red Car'] \
                                example_seed_keywords = ['vehicle']\
                                example_output: {'"+metadataJsonPrimaryKey+"': ['red car', 'red truck', 'blue car']}\
                                Final Input:\
                                image_labels: " + returnText + "\
                                seed_keywords: "
    
    if len(inputMetadataFieldsToAggregate) > 0:
        logger.info("Input Metadata Fields Used: "+str(';'.join(inputMetadataFieldsToAggregate)))
        promptFinalSummarization = promptFinalSummarization + ';'.join(inputMetadataFieldsToAggregate)

    claude_result = invoke_claude_3_with_text(promptFinalSummarization)
    finalText = extract_model_text(claude_result)
    logger.info(returnText)

    #Cleanup the final return text to remove any ```json``` tags
    finalText = finalText.replace("```json", "")
    finalText = finalText.replace("```", "")

    # Transform to new metadata format
    output_data = {
        "type": "metadata",
        "updateType": "update",
        "metadata": []
    }

    try:
        # Parse Claude's JSON response
        keywords_data = json.loads(finalText)
        
        # Create single metadata entry with keywords array
        # Convert the keywords array to a JSON string for metadataValue
        keywords_array = keywords_data.get(metadataJsonPrimaryKey) if isinstance(keywords_data, dict) else None
        if isinstance(keywords_array, list) and all(isinstance(keyword, str) for keyword in keywords_array):
            output_data["metadata"].append({
                "metadataKey": metadataJsonPrimaryKey,
                "metadataValue": json.dumps(keywords_array),
                "metadataValueType": "string"
            })
        else:
            # Fallback: treat entire response as the value
            logger.warning(f"Expected key '{metadataJsonPrimaryKey}' holding a list of keywords not found in Claude response")
            output_data["metadata"].append({
                "metadataKey": metadataJsonPrimaryKey,
                "metadataValue": finalText,
                "metadataValueType": "string"
            })
    except (ValueError, TypeError) as e:
        logger.error(f"Error parsing keywords JSON: {e}")
        # Fallback: treat as plain text
        output_data["metadata"].append({
            "metadataKey": metadataJsonPrimaryKey,
            "metadataValue": finalText,
            "metadataValueType": "string"
        })

    # Convert to JSON string for S3
    finalText = json.dumps(output_data, indent=2)

    #Save list of keywords back to S3 output directory in a JSON text file in S3 Temporary Bucket
    outputTempKey = outputTempKeyDir + metadataFileObjectName
    s3_client.put_object(Body=finalText, Bucket=outputTempBucket, Key=outputTempKey)

    #Save list of keywords back to S3 output directory in a JSON text file in S3 Metadata Bucket (if bucket provided)
    #Save as asset-level metadata
    if(outputMetadataBucket):
        outputMetadataKey = outputMetadataKeyDir + metadataFileObjectName
        s3_client.put_object(Body=finalText, Bucket=outputMetadataBucket, Key=outputMetadataKey)

    return event