import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    docsSidebar: [
        "index",
        {
            type: "category",
            label: "Overview",
            collapsed: false,
            items: [
                "overview/solution-overview",
                "overview/benefits",
                "overview/use-cases",
                "overview/features",
                "overview/costs",
            ],
        },
        {
            type: "category",
            label: "Core Concepts",
            collapsed: true,
            items: [
                "concepts/overview",
                "concepts/databases",
                "concepts/assets",
                "concepts/files-and-versions",
                "concepts/viewers",
                "concepts/pipelines-and-workflows",
                "concepts/metadata-and-schemas",
                "concepts/tags",
                "concepts/subscriptions",
                "concepts/permissions-model",
            ],
        },
        {
            type: "category",
            label: "Architecture",
            collapsed: true,
            items: [
                "architecture/overview",
                "architecture/details",
                "architecture/aws-resources",
                "architecture/security",
                "architecture/networking",
                "architecture/data-model",
            ],
        },
        {
            type: "category",
            label: "Deployment",
            collapsed: true,
            items: [
                "deployment/prerequisites",
                "deployment/plan-your-deployment",
                "deployment/deploy-the-solution",
                "deployment/configuration-reference",
                "deployment/external-s3-setup",
                "deployment/update-the-solution",
                "deployment/uninstall",
            ],
        },
        {
            type: "category",
            label: "User Guide",
            collapsed: true,
            items: [
                "user-guide/getting-started",
                "user-guide/web-interface",
                "user-guide/upload-first-asset",
                "user-guide/asset-management",
                "user-guide/search-and-discovery",
                "user-guide/metadata-management",
                "user-guide/pipelines-and-workflows",
                "user-guide/permissions",
                "user-guide/tags",
                "user-guide/subscriptions",
                "user-guide/api-keys",
                "user-guide/user-management",
            ],
        },
        {
            type: "category",
            label: "Developer Guide",
            collapsed: true,
            items: [
                "developer/setup",
                "developer/backend",
                "developer/frontend",
                "developer/cdk",
                "developer/viewer-plugins",
                "developer/audit-logging",
                "developer/permissions",
                {
                    type: "category",
                    label: "Addons",
                    collapsed: true,
                    items: ["developer/garnet-framework"],
                },
                {
                    type: "category",
                    label: "Pipelines",
                    collapsed: true,
                    items: [
                        "pipelines/overview",
                        "pipelines/potree-viewer",
                        "pipelines/3d-thumbnail",
                        "pipelines/3d-conversion",
                        "pipelines/cad-mesh-extraction",
                        "pipelines/gaussian-splatting",
                        "pipelines/genai-labeling",
                        "pipelines/isaac-lab",
                        "pipelines/rapidpipeline",
                        "pipelines/model-ops",
                        "pipelines/custom-pipelines",
                    ],
                },
                {
                    type: "category",
                    label: "CLI Reference",
                    collapsed: true,
                    items: [
                        "cli/getting-started",
                        "cli/installation",
                        "cli/command-reference",
                        {
                            type: "category",
                            label: "Command Details",
                            collapsed: true,
                            items: [
                                "cli/commands/setup-and-auth",
                                "cli/commands/database",
                                "cli/commands/assets",
                                "cli/commands/files",
                                "cli/commands/tags",
                                "cli/commands/metadata",
                                "cli/commands/search",
                                "cli/commands/workflows",
                                "cli/commands/permissions",
                                "cli/commands/users-and-keys",
                                "cli/commands/industry",
                            ],
                        },
                        "cli/automation",
                    ],
                },
                {
                    type: "category",
                    label: "API Reference",
                    collapsed: true,
                    items: [
                        "api/overview",
                        "api/authentication",
                        "api/databases",
                        "api/assets",
                        "api/asset-versions",
                        "api/files",
                        "api/metadata",
                        "api/search",
                        "api/pipelines",
                        "api/workflows",
                        "api/asset-links",
                        "api/tags",
                        "api/subscriptions",
                        "api/auth",
                    ],
                },
                {
                    type: "category",
                    label: "Utilities",
                    collapsed: true,
                    items: ["developer/utilities/overview", "developer/utilities/reindex"],
                },
                {
                    type: "category",
                    label: "Troubleshooting",
                    collapsed: true,
                    items: [
                        "troubleshooting/common-issues",
                        "troubleshooting/known-limitations",
                        "troubleshooting/faq",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Additional",
            collapsed: true,
            items: [
                "additional/quotas",
                "additional/partner-integrations",
                "additional/viewer-plugins",
                "additional/notices",
                "additional/revisions",
            ],
        },
    ],
};

export default sidebars;
