FROM amazonlinux

#add aws cli
RUN yum install -y unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
RUN unzip awscliv2.zip 
RUN ./aws/install

RUN amazon-linux-extras install python3
RUN pip3 install boto3
RUN mkdir home/scripts
ADD . home/scripts
WORKDIR /home/scripts
CMD ["test.py"]
ENTRYPOINT [ "python3" ]

