#  Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

"""Tests for the metadataGenerationPipeline lambda's handling of the model response and of the final
summarization prompt's seed keywords.

Two behaviours are covered. First, the response shape: the content blocks are read through one guard
that names the shape it rejected, so a model that legitimately returned no content blocks is
distinguishable in the raised error from a malformed or non-object response, and a parsed value that
is not a keyword list falls back to the raw text rather than writing a JSON object into a field typed
`string`. Second, the seed metadata: the final summarization prompt's `seed_keywords:` label is filled
from the aggregated metadata fields, which is the pass that decides the stored keyword set.
"""

import os
import sys
import json
import types
import importlib.util
from unittest.mock import MagicMock, patch

import pytest

_LAMBDA_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _LAMBDA_DIR not in sys.path:
    sys.path.insert(0, _LAMBDA_DIR)

# Stub customLogging so the lambda imports without aws_lambda_powertools.
if "customLogging" not in sys.modules:
    _cl_pkg = types.ModuleType("customLogging")
    _cl_logger = types.ModuleType("customLogging.logger")
    _cl_logger.safeLogger = lambda **kw: MagicMock()
    _cl_pkg.logger = _cl_logger
    sys.modules["customLogging"] = _cl_pkg
    sys.modules["customLogging.logger"] = _cl_logger

for _k, _v in {
    "AWS_DEFAULT_REGION": "us-east-1",
    "AWS_REGION": "us-east-1",
    "BEDROCK_MODEL_ID": "anthropic.claude-3-sonnet-20240229-v1:0",
}.items():
    os.environ.setdefault(_k, _v)


_HANDLER = os.path.join(_LAMBDA_DIR, "metadataGenerationPipeline.py")
_MODULE_NAME = "_metadata_generation_for_model_response_tests"


def _load():
    """This pipeline's own handler, loaded by path under a name no other suite uses.

    Every pipeline's tests put their own lambda directory on ``sys.path``, so a bare-name import
    binds to whichever copy of a shared module name reached ``sys.modules`` first. This module name
    is unique to this pipeline today; loading by path keeps it asserted rather than assumed.
    """
    module = sys.modules.get(_MODULE_NAME)
    if module is None:
        spec = importlib.util.spec_from_file_location(_MODULE_NAME, _HANDLER)
        module = importlib.util.module_from_spec(spec)
        sys.modules[_MODULE_NAME] = module
        spec.loader.exec_module(module)
    assert module.__file__ == _HANDLER, \
        f"loaded {module.__file__}, expected this pipeline's own copy at {_HANDLER}"
    return module


def _definition():
    return {
        "jobName": "PipelineJob_x",
        "stages": [
            {"type": "BLENDERRENDERER"},
            {
                "type": "METADATAGENERATION",
                "inputFile": {"bucketName": "aux", "objectDir": "xidM/imgs/"},
                "outputFiles": {"bucketName": "", "objectDir": ""},
                "outputMetadata": {"bucketName": "asset-bucket", "objectDir": "xidM/metadata/"},
                "temporaryFiles": {"bucketName": "aux", "objectDir": "xidM/imgs/"},
            },
        ],
        "inputMetadataS3Location": "s3://abkt/pipelines/workflowExecutionInputs/E1/metadata.json",
        "inputConfigurationS3Location": "s3://abkt/pipelines/workflowExecutionInputs/E1/p1/config.json",
        "externalSfnTaskToken": "tok",
    }


def _grouped_metadata_envelope():
    """The run metadata file: the grouped-by-asset envelope (schemaVersion 2)."""
    return {
        "schemaVersion": 2,
        "assets": [{
            "databaseId": "dbM", "assetId": "xidM",
            "assetData": {"assetName": "Pump"},
            "files": [
                {"fileKey": "/", "metadata": {"PART": "centrifugal pump"}},
                {"fileKey": "/test/pump.glb", "metadata": {"REVISION": "C"},
                 "attributes": {"UNITS": "mm"}},
            ],
        }],
    }


def _text_response(text):
    return {"usage": {"input_tokens": 1, "output_tokens": 2}, "content": [{"text": text}]}


def _keywords_response(keywords):
    return _text_response(json.dumps({"autoGeneratedKeywords": keywords}))


def _drive(mod, image_response, final_response, seed_gate="False", metadata_envelope=None,
           rekognition_labels=("pump",), captured=None):
    """Run lambda_handler with scripted model responses.

    Returns (prompts, put_objects); prompts entries are (prompt, had_image) so the per-image prompts
    and the single final summarization prompt can be told apart. `captured` is filled with the S3
    writes even when the handler raises, which is how a route that must write nothing is asserted.
    """
    prompts = []
    config_obj = {"seedMetadataGenerationWithInputMetadata": seed_gate}
    metadata_envelope = metadata_envelope if metadata_envelope is not None else _grouped_metadata_envelope()

    def fake_get_object(Bucket, Key):
        payload = config_obj if Key.endswith("config.json") else metadata_envelope
        return {"Body": MagicMock(read=lambda: json.dumps(payload).encode("utf-8"))}

    def fake_claude(prompt, base64_image_data=None):
        prompts.append((prompt, base64_image_data is not None))
        return image_response if base64_image_data is not None else final_response

    labels = [MagicMock(confidence=99.0, name=name) for name in rekognition_labels]
    for label, name in zip(labels, rekognition_labels):
        label.name = name

    event = {"definition": [json.dumps(_definition())]}
    with patch.object(mod, "s3_client") as s3, \
            patch.object(mod, "get_all_image_files_in_path",
                         MagicMock(return_value=[{"key": "xidM/imgs/a.png", "relativePath": "a.png"}])), \
            patch.object(mod, "image_to_base64", MagicMock(return_value="b64")), \
            patch.object(mod, "invoke_claude_3_with_text", side_effect=fake_claude), \
            patch.object(mod, "RekognitionImage") as rek, \
            patch("os.path.exists", MagicMock(return_value=False)):
        s3.get_object.side_effect = fake_get_object
        s3.download_file = MagicMock()
        s3.put_object = MagicMock()
        rek.from_file.return_value.detect_labels.return_value = labels
        try:
            mod.lambda_handler(event, MagicMock())
        finally:
            if captured is not None:
                captured["put_objects"] = [json.loads(call.kwargs["Body"])
                                           for call in s3.put_object.call_args_list]

    put_objects = [json.loads(call.kwargs["Body"]) for call in s3.put_object.call_args_list]
    return prompts, put_objects


def _drive_real_invoke(mod, image_body_bytes, final_body_bytes):
    """Run lambda_handler with the raw bytes the Bedrock response stream yields, so
    `invoke_claude_3_with_text` itself runs and its own shape guard applies.

    `_drive` replaces that function wholesale, which is the right tool for the handler's own
    branching but leaves the invoke boundary untested: a response body that is not a JSON object is
    rejected inside the invoke, before the handler sees a value at all, so which of the two call
    sites tolerates that shape is only observable from here.

    Returns (raised, put_objects).
    """
    def fake_invoke_model(modelId, body):
        blocks = json.loads(body)["messages"][0]["content"]
        has_image = any(block.get("type") == "image" for block in blocks)
        return {"body": MagicMock(read=lambda: image_body_bytes if has_image else final_body_bytes)}

    def fake_get_object(Bucket, Key):
        payload = ({"seedMetadataGenerationWithInputMetadata": "False"}
                   if Key.endswith("config.json") else _grouped_metadata_envelope())
        return {"Body": MagicMock(read=lambda: json.dumps(payload).encode("utf-8"))}

    label = MagicMock(confidence=99.0)
    label.name = "pump"

    event = {"definition": [json.dumps(_definition())]}
    raised = None
    with patch.object(mod, "s3_client") as s3, \
            patch.object(mod.bedrock_client, "invoke_model", side_effect=fake_invoke_model), \
            patch.object(mod, "get_all_image_files_in_path",
                         MagicMock(return_value=[{"key": "xidM/imgs/a.png", "relativePath": "a.png"}])), \
            patch.object(mod, "image_to_base64", MagicMock(return_value="b64")), \
            patch.object(mod, "RekognitionImage") as rek, \
            patch("os.path.exists", MagicMock(return_value=False)):
        s3.get_object.side_effect = fake_get_object
        s3.download_file = MagicMock()
        s3.put_object = MagicMock()
        rek.from_file.return_value.detect_labels.return_value = [label]
        try:
            mod.lambda_handler(event, MagicMock())
        except Exception as e:  # noqa: BLE001 - the assertion is about which route survives
            raised = e
        put_objects = [json.loads(call.kwargs["Body"]) for call in s3.put_object.call_args_list]
    return raised, put_objects


def _final_prompt(prompts):
    finals = [prompt for prompt, had_image in prompts if not had_image]
    assert len(finals) == 1, f"expected one summarization call, got {len(finals)}"
    return finals[0]


def _written_value(put_objects):
    assert put_objects, "nothing was written to S3"
    body = put_objects[0]
    assert body["type"] == "metadata"
    assert body["updateType"] == "update"
    assert isinstance(body["metadata"], list) and len(body["metadata"]) == 1
    entry = body["metadata"][0]
    assert entry["metadataKey"] == "autoGeneratedKeywords"
    assert entry["metadataValueType"] == "string"
    return entry["metadataValue"]


# ============================ response-shape guard ============================

@pytest.mark.unit
class TestExtractModelText:
    def test_reads_the_first_content_block(self):
        mod = _load()
        assert mod.extract_model_text(_text_response("pump, impeller")) == "pump, impeller"

    def test_each_rejected_shape_names_itself(self):
        """An empty content list must be distinguishable from a malformed response."""
        mod = _load()
        cases = {
            "non-object": None,
            "no content field": {"usage": {}},
            "content not a list": {"content": {"text": "x"}},
            "empty content list": {"content": []},
            "block without text": {"content": [{"type": "tool_use", "id": "t1"}]},
        }
        messages = {}
        for label, response in cases.items():
            with pytest.raises(mod.ModelResponseError) as excinfo:
                mod.extract_model_text(response)
            messages[label] = str(excinfo.value)

        assert "not a JSON object" in messages["non-object"]
        assert "no 'content' field" in messages["no content field"]
        assert "'content' is not a list" in messages["content not a list"]
        assert "empty 'content' list" in messages["empty content list"]
        assert "no 'text' string" in messages["block without text"]
        # Every shape reports a different cause, so the execution record says which one occurred.
        assert len(set(messages.values())) == len(cases)

        with pytest.raises(mod.ModelResponseError) as excinfo:
            mod.extract_model_text({"content": [{"text": 42}]})
        assert "no 'text' string" in str(excinfo.value)

    def test_invoke_tolerates_a_block_without_text(self):
        """The logging of the returned blocks must not be what fails on an unexpected block shape."""
        mod = _load()
        body = {"usage": {"input_tokens": 1, "output_tokens": 2},
                "content": [{"type": "tool_use", "id": "t1"}]}
        response = {"body": MagicMock(read=lambda: json.dumps(body).encode("utf-8"))}
        with patch.object(mod.bedrock_client, "invoke_model", MagicMock(return_value=response)):
            result = mod.invoke_claude_3_with_text("prompt")
        assert result == body
        with pytest.raises(mod.ModelResponseError) as excinfo:
            mod.extract_model_text(result)
        assert "no 'text' string" in str(excinfo.value)

    def test_invoke_rejects_a_non_object_body(self):
        mod = _load()
        response = {"body": MagicMock(read=lambda: b"null")}
        with patch.object(mod.bedrock_client, "invoke_model", MagicMock(return_value=response)):
            with pytest.raises(mod.ModelResponseError) as excinfo:
                mod.invoke_claude_3_with_text("prompt")
        assert "not a JSON object" in str(excinfo.value)


# ============================ handler behaviour on odd model output ============================

@pytest.mark.unit
class TestHandlerModelOutput:
    def test_final_summarization_null_response_reports_the_shape(self):
        """The old failure was an unguarded index/`in` test; the cause must now name the shape."""
        mod = _load()
        captured = {}
        with pytest.raises(mod.ModelResponseError) as excinfo:
            _drive(mod, image_response=_text_response("pump"), final_response=None,
                   captured=captured)
        assert "not a JSON object" in str(excinfo.value)
        # Reporting SUCCESS with an empty keyword set is what the raise exists to prevent, so the
        # route must also leave no metadata object behind.
        assert captured["put_objects"] == []

    def test_final_summarization_empty_content_reports_the_empty_list(self):
        mod = _load()
        captured = {}
        with pytest.raises(mod.ModelResponseError) as excinfo:
            _drive(mod, image_response=_text_response("pump"), final_response={"content": []},
                   captured=captured)
        assert "empty 'content' list" in str(excinfo.value)
        assert captured["put_objects"] == []

    def test_per_image_response_without_text_does_not_fail_the_run(self):
        """One unusable per-image response is skipped: the other images and Rekognition still count."""
        mod = _load()
        prompts, put_objects = _drive(
            mod, image_response={"content": []}, final_response=_keywords_response(["pump"]))
        # The Rekognition label from that same image still reached the summarization prompt.
        assert "pump" in _final_prompt(prompts)
        assert json.loads(_written_value(put_objects)) == ["pump"]

    def test_keyword_list_is_written_as_a_json_string(self):
        mod = _load()
        _prompts, put_objects = _drive(
            mod, image_response=_text_response("pump, impeller"),
            final_response=_keywords_response(["pump", "impeller"]))
        assert json.loads(_written_value(put_objects)) == ["pump", "impeller"]

    def test_non_list_keyword_value_falls_back_to_the_raw_text(self):
        """A JSON object under the expected key must not be written into a `string` field."""
        mod = _load()
        raw = json.dumps({"autoGeneratedKeywords": {"a": 1}})
        _prompts, put_objects = _drive(
            mod, image_response=_text_response("pump"), final_response=_text_response(raw))
        assert _written_value(put_objects) == raw

    def test_list_of_non_strings_falls_back_to_the_raw_text(self):
        mod = _load()
        raw = json.dumps({"autoGeneratedKeywords": [{"keyword": "pump"}]})
        _prompts, put_objects = _drive(
            mod, image_response=_text_response("pump"), final_response=_text_response(raw))
        assert _written_value(put_objects) == raw

    @pytest.mark.parametrize("raw", ["null", "42", '"pump, impeller"'])
    def test_scalar_json_response_falls_back_without_raising(self, raw):
        """`null` and a bare number parse cleanly, then used to raise TypeError past every handler."""
        mod = _load()
        _prompts, put_objects = _drive(
            mod, image_response=_text_response("pump"), final_response=_text_response(raw))
        assert _written_value(put_objects) == raw

    def test_unparseable_response_still_falls_back(self):
        mod = _load()
        _prompts, put_objects = _drive(
            mod, image_response=_text_response("pump"), final_response=_text_response("not json at all"))
        assert _written_value(put_objects) == "not json at all"


# ============================ the two call sites at the invoke boundary ============================

@pytest.mark.unit
class TestTheModelInvokeBoundary:
    """The two call sites treat an unusable response differently, and a response body that is not a
    JSON object is rejected inside the invoke rather than by the handler's own extraction. These
    arms drive the real invoke so the difference between the two sites is observable for that shape
    as well as for the ones the handler rejects itself."""

    @pytest.mark.parametrize("body", [b"null", b"42", b'[{"text": "pump"}]'])
    def test_a_per_image_non_object_response_is_skipped(self, body):
        """One image's response being unusable must not end the run: the remaining images and
        Rekognition still contribute, and the keyword list is still written."""
        mod = _load()
        raised, put_objects = _drive_real_invoke(
            mod, image_body_bytes=body,
            final_body_bytes=json.dumps(_keywords_response(["pump"])).encode("utf-8"))
        assert raised is None, f"the per-image {body!r} response failed the run: {raised!r}"
        assert json.loads(_written_value(put_objects)) == ["pump"]

    def test_the_final_non_object_response_fails_the_run_and_writes_nothing(self):
        """Control for the arm above: the same shape on the summarization call has nothing to store,
        so it fails the execution with the shape named."""
        mod = _load()
        raised, put_objects = _drive_real_invoke(
            mod, image_body_bytes=json.dumps(_text_response("pump")).encode("utf-8"),
            final_body_bytes=b"null")
        assert isinstance(raised, mod.ModelResponseError), repr(raised)
        assert "not a JSON object" in str(raised)
        assert put_objects == []

    def test_an_ordinary_run_crosses_the_real_invoke_unchanged(self):
        mod = _load()
        raised, put_objects = _drive_real_invoke(
            mod, image_body_bytes=json.dumps(_text_response("pump, impeller")).encode("utf-8"),
            final_body_bytes=json.dumps(_keywords_response(["pump", "impeller"])).encode("utf-8"))
        assert raised is None, repr(raised)
        assert json.loads(_written_value(put_objects)) == ["pump", "impeller"]


# ============================ seed keywords in the final prompt ============================

@pytest.mark.unit
class TestSeedKeywordsInFinalPrompt:
    def test_seed_fields_are_appended_after_the_label(self):
        """The summarization pass is the one that filters outliers, so it needs the seed context."""
        mod = _load()
        prompts, _put_objects = _drive(
            mod, image_response=_text_response("pump"),
            final_response=_keywords_response(["pump"]), seed_gate="True")
        final = _final_prompt(prompts)
        label_index = final.rindex("seed_keywords: ")
        after_label = final[label_index + len("seed_keywords: "):]
        assert after_label != "", "the seed_keywords label was left empty"
        # Every scope of the grouped metadata envelope seeds the pass.
        assert "PART:::centrifugal pump" in after_label
        assert "REVISION:::C" in after_label
        assert "UNITS:::mm" in after_label

    def test_no_seed_fields_when_the_gate_is_off(self):
        mod = _load()
        prompts, _put_objects = _drive(
            mod, image_response=_text_response("pump"),
            final_response=_keywords_response(["pump"]), seed_gate="False")
        final = _final_prompt(prompts)
        assert final.endswith("seed_keywords: ")
        assert ":::" not in final

    def test_per_image_prompt_keeps_its_seed_fields(self):
        """The per-image prompt already carried the seed list; the fix must not disturb it."""
        mod = _load()
        prompts, _put_objects = _drive(
            mod, image_response=_text_response("pump"),
            final_response=_keywords_response(["pump"]), seed_gate="True")
        per_image = [prompt for prompt, had_image in prompts if had_image]
        assert len(per_image) == 1
        assert "PART:::centrifugal pump" in per_image[0]
