/*
 * Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTemplates, useTemplateMutations, usePipeline } from "../api/queries";
import type { Template, ConfigFormat, TagSchemaField } from "../types";
import ConfigEditor from "../components/ConfigEditor";
import DynamicTagForm from "../components/DynamicTagForm";
import TagSchemaBuilder from "./TagSchemaBuilder";
import TemplateOverridesEditor from "./TemplateOverridesEditor";
import Stepper from "../components/Stepper";
import InfoTooltip from "../components/InfoTooltip";
import Breadcrumb from "../components/Breadcrumb";
import { btnPrimary, btnSecondary } from "../components/controlStyles";

interface TemplateFormProps {
    mode: "create" | "edit";
    databaseId: string;
    pipelineId: string;
    /** The template being edited (edit mode). */
    initial?: Template;
}

const CONFIG_FORMATS: ConfigFormat[] = ["json", "yaml", "openjd", "xml", "raw"];

const STEPS = [
    { id: "basic", label: "Basic" },
    { id: "config", label: "Configuration" },
    { id: "tags", label: "Tags" },
    { id: "review", label: "Review" },
];

/**
 * Full-page create/edit Template wizard (mirrors the pipeline/workflow builder pages). Reached from
 * the pipeline's Templates list. Steps: Basic → Configuration → Tags → Review.
 */
const TemplateForm: React.FC<TemplateFormProps> = ({ mode, databaseId, pipelineId, initial }) => {
    const navigate = useNavigate();
    const { createTemplate, updateTemplate } = useTemplateMutations();
    const { data: pipeline } = usePipeline(databaseId, pipelineId);
    const pipelineLabel = pipeline?.pipelineName || pipelineId;

    const [templateName, setTemplateName] = useState(initial?.templateName || "");
    const [description, setDescription] = useState(initial?.description || "");
    const [configFormat, setConfigFormat] = useState<ConfigFormat>(initial?.configFormat || "json");
    const [configBody, setConfigBody] = useState(initial?.configBody || "");
    const [inputInstructions, setInputInstructions] = useState(initial?.inputInstructions || "");
    const [allowCustomEdit, setAllowCustomEdit] = useState(initial?.allowCustomEdit || false);
    const [isDefault, setIsDefault] = useState(initial?.isDefault || false);
    // Structured overrides object (subset of pipeline systemConfig keys); empty = inherit pipeline.
    const [overrides, setOverrides] = useState<Record<string, any>>(initial?.overrides || {});
    const [tagSchema, setTagSchema] = useState<TagSchemaField[]>(initial?.tagSchema || []);
    const [saveError, setSaveError] = useState<string | null>(null);
    const [wizardStep, setWizardStep] = useState<string>("basic");

    const stepIndex = STEPS.findIndex((s) => s.id === wizardStep);
    const isLastStep = stepIndex === STEPS.length - 1;

    // Per-step validation: the Basic step requires a template name before advancing (and it is
    // required to save at all). Other steps have no blocking requirements.
    const basicError = !templateName.trim() ? "Template name is required" : null;
    const canAdvance = wizardStep === "basic" ? !basicError : true;

    const done = () => navigate(`/databases/${databaseId}/pipelines/${pipelineId}/templates`);

    const handleSave = async () => {
        const configBodySize = new Blob([configBody]).size;
        const webFormJsonSize = new Blob([JSON.stringify(tagSchema)]).size;
        if (configBodySize + webFormJsonSize > 6 * 1024 * 1024) {
            setSaveError(
                `Combined size exceeds the 6MB limit (current: ${(
                    (configBodySize + webFormJsonSize) /
                    1024 /
                    1024
                ).toFixed(2)}MB)`
            );
            return;
        }

        const templateData: Partial<Template> = {
            templateName,
            description,
            configFormat,
            configBody,
            inputInstructions,
            allowCustomEdit,
            isDefault,
            overrides,
            tagSchema,
            webFormJson: JSON.stringify(tagSchema),
        };

        try {
            if (mode === "edit" && initial) {
                await updateTemplate.mutateAsync({
                    databaseId,
                    pipelineId,
                    templateId: initial.templateId,
                    body: templateData,
                });
            } else {
                // templateId is generated by the backend when omitted; the web does not set it.
                await createTemplate.mutateAsync({
                    databaseId,
                    pipelineId,
                    body: { databaseId, pipelineId, ...templateData } as Template,
                });
            }
            done();
        } catch (err: any) {
            setSaveError(err?.message || "Failed to save template");
        }
    };

    return (
        <div className="orchestration-root p-6 space-y-6 bg-surface min-h-full">
            <div className="space-y-1">
                <Breadcrumb
                    items={[
                        { label: "Pipelines", to: `/databases/${databaseId}/pipelines` },
                        {
                            label: pipelineLabel,
                            to: `/databases/${databaseId}/pipelines/${pipelineId}`,
                        },
                        {
                            label: "Templates",
                            to: `/databases/${databaseId}/pipelines/${pipelineId}/templates`,
                        },
                        {
                            label:
                                mode === "create"
                                    ? "Create Template"
                                    : initial?.templateName || "Edit Template",
                        },
                    ]}
                />
                <h1 className="text-2xl font-semibold text-text-primary">
                    {mode === "create" ? "Create Template" : "Edit Template"}
                </h1>
            </div>

            <Stepper steps={STEPS} current={wizardStep} />

            <div className="bg-surface-container border border-border-default rounded-lg p-4 space-y-4">
                {wizardStep === "basic" && (
                    <>
                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Template Name *
                            </label>
                            <input
                                type="text"
                                value={templateName}
                                onChange={(e) => setTemplateName(e.target.value)}
                                className="w-full px-3 py-2 border border-border-input rounded bg-surface-input text-text-primary"
                                placeholder="Template name"
                            />
                            {basicError && (
                                <p className="text-vams-error text-sm mt-1">{basicError}</p>
                            )}
                        </div>
                        <div>
                            <label className="block text-sm font-medium mb-1">Description</label>
                            <textarea
                                value={description}
                                onChange={(e) => setDescription(e.target.value)}
                                className="w-full px-3 py-2 border border-border-input rounded bg-surface-input text-text-primary"
                                rows={2}
                                placeholder="Template description"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Input Instructions
                            </label>
                            <textarea
                                value={inputInstructions}
                                onChange={(e) => setInputInstructions(e.target.value)}
                                className="w-full px-3 py-2 border border-border-input rounded bg-surface-input text-text-primary"
                                rows={2}
                                placeholder="Instructions shown to the person running an execution with this template"
                            />
                        </div>
                        <div>
                            <label className="flex items-center space-x-2">
                                <input
                                    type="checkbox"
                                    checked={isDefault}
                                    onChange={(e) => setIsDefault(e.target.checked)}
                                    className="w-4 h-4"
                                />
                                <span className="text-sm">
                                    Set as the pipeline's default template
                                </span>
                                <InfoTooltip text="The default template is pre-selected first on the execute form, and is auto-selected by the backend when a require-template pipeline runs without a template chosen. Only one template per pipeline can be the default — setting this clears any prior default." />
                            </label>
                        </div>
                    </>
                )}

                {wizardStep === "config" && (
                    <>
                        <div>
                            <label className="block text-sm font-medium mb-1">
                                Config Format *
                            </label>
                            <select
                                value={configFormat}
                                onChange={(e) => setConfigFormat(e.target.value as ConfigFormat)}
                                className="w-full px-3 py-2 border border-border-input rounded bg-surface-input text-text-primary"
                            >
                                {CONFIG_FORMATS.map((format) => (
                                    <option key={format} value={format}>
                                        {format}
                                    </option>
                                ))}
                            </select>
                        </div>
                        <div>
                            <div className="flex items-center gap-1.5 text-sm font-medium mb-1">
                                Config Body
                                <InfoTooltip text="The configuration body delivered to the pipeline. Use {{tagName}} placeholders that the tag schema fills at launch." />
                            </div>
                            <ConfigEditor
                                value={configBody}
                                language={configFormat}
                                onChange={(val) => setConfigBody(val || "")}
                                height="300px"
                            />
                        </div>
                        <div>
                            <label className="flex items-center space-x-2">
                                <input
                                    type="checkbox"
                                    checked={allowCustomEdit}
                                    onChange={(e) => setAllowCustomEdit(e.target.checked)}
                                    className="w-4 h-4"
                                />
                                <span className="text-sm">
                                    Allow editing the config body at execution time
                                </span>
                                <InfoTooltip text="When on, the person running an execution with this template may edit the config body inline before launch (a one-off change for that run)." />
                            </label>
                        </div>
                        <div>
                            <div className="flex items-center gap-1.5 text-sm font-medium mb-2">
                                Pipeline setting overrides
                                <InfoTooltip text="Optional. Overrides the pipeline's input-handling settings for executions that use this template (input file count, asset selection rules, metadata inputs, input-file filters). This does NOT edit the config body. Anything left un-toggled inherits the pipeline's value." />
                            </div>
                            <TemplateOverridesEditor value={overrides} onChange={setOverrides} />
                        </div>
                    </>
                )}

                {wizardStep === "tags" && (
                    <>
                        <div>
                            <div className="flex items-center gap-1.5 text-sm font-medium mb-1">
                                Tag Schema
                                <InfoTooltip text="Typed tags that fill the {{tagName}} placeholders in the config body. Each tag becomes a field on the execute form." />
                            </div>
                            <p className="text-xs text-text-secondary mb-2">
                                These tags define the execute-time form for this template — one
                                input field per tag. They fill the <code>{"{{tagName}}"}</code>{" "}
                                placeholders in the config body.
                            </p>
                            <TagSchemaBuilder value={tagSchema} onChange={setTagSchema} />
                        </div>
                        {tagSchema.length > 0 && (
                            <div>
                                <div className="flex items-center gap-1.5 text-sm font-medium mb-2">
                                    Live preview
                                    <InfoTooltip text="How the tag fields appear on the execute form when this template is chosen." />
                                </div>
                                <div className="rounded-lg border border-border-default bg-surface-secondary p-4">
                                    <div className="text-xs text-text-secondary mb-3">
                                        Execute-form preview
                                    </div>
                                    <DynamicTagForm schema={tagSchema} />
                                </div>
                            </div>
                        )}
                    </>
                )}

                {wizardStep === "review" && (
                    <div className="text-sm text-text-primary space-y-1">
                        <div>
                            <span className="text-text-secondary">Name:</span> {templateName || "—"}
                        </div>
                        <div>
                            <span className="text-text-secondary">Format:</span> {configFormat}
                        </div>
                        <div>
                            <span className="text-text-secondary">Allow custom edit:</span>{" "}
                            {allowCustomEdit ? "Yes" : "No"}
                        </div>
                        <div>
                            <span className="text-text-secondary">Default template:</span>{" "}
                            {isDefault ? "Yes" : "No"}
                        </div>
                        <div>
                            <span className="text-text-secondary">Tags:</span> {tagSchema.length}
                        </div>
                    </div>
                )}

                {saveError && (
                    <div className="p-3 bg-red-100 dark:bg-red-900 border border-red-300 dark:border-red-700 rounded">
                        <p className="text-sm text-red-800 dark:text-red-200">{saveError}</p>
                    </div>
                )}
            </div>

            <div className="flex justify-between gap-2">
                <button onClick={done} className={btnSecondary}>
                    Cancel
                </button>
                <div className="flex gap-2">
                    {stepIndex > 0 && (
                        <button
                            onClick={() => setWizardStep(STEPS[stepIndex - 1].id)}
                            className={btnSecondary}
                        >
                            Back
                        </button>
                    )}
                    {!isLastStep ? (
                        <button
                            onClick={() => setWizardStep(STEPS[stepIndex + 1].id)}
                            disabled={!canAdvance}
                            className={btnPrimary}
                        >
                            Next
                        </button>
                    ) : (
                        <button
                            onClick={handleSave}
                            disabled={
                                !!basicError || createTemplate.isPending || updateTemplate.isPending
                            }
                            className={btnPrimary}
                        >
                            {createTemplate.isPending || updateTemplate.isPending
                                ? "Saving..."
                                : "Save"}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default TemplateForm;

/** Edit-mode wrapper that resolves the template from the pipeline's template list by id. */
export const TemplateFormEditLoader: React.FC<{
    databaseId: string;
    pipelineId: string;
    templateId: string;
}> = ({ databaseId, pipelineId, templateId }) => {
    const { data: templates = [], isLoading } = useTemplates(databaseId, pipelineId);
    if (isLoading) {
        return (
            <div className="flex items-center justify-center min-h-screen bg-surface text-text-primary">
                <div className="text-center">
                    <div className="inline-block animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600 dark:border-blue-400 mb-3" />
                    <p className="text-text-secondary">Loading template…</p>
                </div>
            </div>
        );
    }
    const template = templates.find((t) => t.templateId === templateId);
    if (!template) {
        return (
            <div className="flex items-center justify-center min-h-screen bg-surface text-text-primary">
                <p className="text-vams-error text-xl">Template not found</p>
            </div>
        );
    }
    return (
        <TemplateForm
            mode="edit"
            databaseId={databaseId}
            pipelineId={pipelineId}
            initial={template}
        />
    );
};
