/*
 * Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

export const RESERVED_TAG_KEYS = new Set<string>([
    "assetDataObject",
    "assetFileAssetIdArray",
    "assetFileCount",
    "assetFileDatabaseIdArray",
    "assetFileKeyArray",
    "assetFileObjectArray",
    "assetFileRelativePathArray",
    "assetFileS3UriArray",
    "assetFileUniqueAssetIdArray",
    "assetFileUniqueDatabaseIdArray",
    "assetFileVersionIdArray",
    "assetMetadataObject",
    "auxBucket",
    "auxPreviewPipelineSuffix",
    "auxTempPrefix",
    "auxTempS3Uri",
    "databaseMetadataObject",
    "deadlineFarmId",
    "deadlineQueueId",
    "deadlineStorageProfileId",
    "executingUserName",
    "executionId",
    "executionStartTimestamp",
    "fileAttributesObject",
    "fileMetadataObject",
    "firstAssetFileAssetBucket",
    "firstAssetFileAssetId",
    "firstAssetFileAssetRootS3Key",
    "firstAssetFileAuxPreviewPrefix",
    "firstAssetFileAuxPreviewS3Uri",
    "firstAssetFileDatabaseId",
    "firstAssetFileFileExtension",
    "firstAssetFileFileName",
    "firstAssetFileFileNameNoExt",
    "firstAssetFileKey",
    "firstAssetFileRelativePath",
    "firstAssetFileS3Uri",
    "firstAssetFileVersionId",
    "inputConfigurationS3Location",
    "inputMetadataObject",
    "inputMetadataS3Location",
    "jobName",
    "jobStartDate",
    "jobStartTimestamp",
    "jobStartTimestampUnix",
    "orchestrationBusArn",
    "orchestrationEventPrefix",
    "outputBucket",
    "outputFileBaseExecutionPathExtension",
    "outputFilesPrefix",
    "outputFilesS3Uri",
    "outputMetadataPrefix",
    "outputMetadataS3Uri",
    "outputPreviewsPrefix",
    "outputPreviewsS3Uri",
    "outputResultsPrefix",
    "outputResultsS3Uri",
    "outputTargetAssetId",
    "outputTargetAssetRootS3Key",
    "outputTargetDatabaseId",
    "outputTargetLocationType",
    "pipelineDatabaseId",
    "pipelineExecutionId",
    "pipelineId",
    "pipelineName",
    "triggerType",
    "workflowDatabaseId",
    "workflowId",
]);

export const METADATA_DYNAMIC_TAG_PREFIX = "metadata_";

export function isReservedTagKey(key: string): boolean {
    return !!key && (RESERVED_TAG_KEYS.has(key) || key.startsWith(METADATA_DYNAMIC_TAG_PREFIX));
}
