# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM python:3.11-alpine

#Build PotreeConverter
WORKDIR /PotreeConverterBuild

# install build deps, download Potree Source, and build for Potree Conveter
RUN apk add --no-cache git cmake make gcc g++ libtbb-dev && \
    git clone --depth 1 --branch $VERSION https://github.com/potree/PotreeConverter /PotreeConverter || \
    git clone --depth 1 https://github.com/potree/PotreeConverter /PotreeConverter

# Copy a git patch for the local CMakeLists.txt so we can override compiler settings
COPY ./PotreeConverter-Fork_af4666fa.patch /PotreeConverter/vams-potree-build.patch

# Potree Converter Commit Hash Reset && Apply the git patch 
WORKDIR /PotreeConverter
RUN git reset --hard af4666fa1090983d8ce7c11dcf49ba19eda90995
RUN git apply --whitespace=fix vams-potree-build.patch
WORKDIR /PotreeConverterBuild

RUN cmake /PotreeConverter 
RUN make && \
    apk del git cmake make gcc g++ && \
    rm -rf /PotreeConverter

# python environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy python scripts app to container
COPY ./ ./pc_pipeline

# install python app and deps
RUN pip3 install -r ./pc_pipeline/requirements.txt

# set entry point to app
ENTRYPOINT ["python3", "-m", "pc_pipeline"]