FROM public.ecr.aws/docker/library/python:3.12-alpine

#Install blender + openCV (has all the libraries needed for blender rendering)
RUN apk add --no-cache blender=4.1.1-r2 py3-numpy py3-opencv

# python environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy python scripts app to container
COPY ./ ./

# upgrade pip
RUN pip install --upgrade pip

# install python app and deps
RUN pip3 install -r ./requirements.txt

# set entry point to app
ENTRYPOINT ["python3", "-m", "main"]