/*
 * Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Declarative field metadata that drives the form UI. Field labels/help mirror
 * documentation/docusaurus-site/docs/deployment/configuration-reference.md.
 *
 * Essentials-first: fields without `advanced: true` are always visible in
 * their section. Whole sections marked `advanced` start collapsed.
 *
 * This file describes *what to render*. The cross-field rules live separately
 * in validation.ts (the fidelity contract against config.ts).
 */

import type { ConfigShape, FieldMeta, Section } from "./types";
import { getByPath } from "./pathUtils";

export const SECTIONS: Section[] = [
    {
        id: "essentials",
        label: "Deployment basics",
        description: "The minimum required to produce a deployable configuration.",
        order: 1,
    },
    {
        id: "security",
        label: "Security & compliance",
        description: "WAF, FIPS, KMS encryption, and GovCloud / IL6 mode.",
        order: 2,
    },
    {
        id: "networking",
        label: "Networking (VPC)",
        description:
            "VPC creation or import. Auto-enabled by ALB, provisioned OpenSearch, and container pipelines.",
        order: 3,
    },
    {
        id: "frontend",
        label: "Web distribution (CloudFront / ALB)",
        description: "Choose exactly one static-website host. GovCloud requires ALB.",
        order: 4,
    },
    {
        id: "search",
        label: "Search (OpenSearch)",
        description: "Optional. Enable at most one of Serverless or Provisioned.",
        order: 5,
    },
    {
        id: "auth",
        label: "Authentication",
        description: "Exactly one auth method: Amazon Cognito or an external OAuth IdP.",
        order: 6,
    },
    {
        id: "pipelines-standard",
        label: "Pipelines — standard",
        description: "3D conversion, previews, and metadata extraction.",
        advanced: true,
        order: 7,
    },
    {
        id: "pipelines-gpu",
        label: "Pipelines — NVIDIA / GPU & third-party",
        description:
            "GPU-backed pipelines: Cosmos, Gr00t, Isaac Lab, Gaussian Splatting, RapidPipeline, ModelOps.",
        advanced: true,
        order: 8,
    },
    {
        id: "addons",
        label: "Add-ons (Garnet Framework)",
        advanced: true,
        order: 9,
    },
    {
        id: "api-webui",
        label: "API throttling & Web UI",
        advanced: true,
        order: 10,
    },
    {
        id: "metadata",
        label: "Metadata schema auto-load",
        advanced: true,
        order: 11,
    },
];

// --- Visibility predicates (shared) ---
const albEnabled = (c: ConfigShape) => !!getByPath(c, "app.useAlb.enabled");
const cfCustomDomain = (c: ConfigShape) => !!getByPath(c, "app.useCloudFront.customDomain.enabled");
const provisioned = (c: ConfigShape) => !!getByPath(c, "app.openSearch.useProvisioned.enabled");
const serverless = (c: ConfigShape) => !!getByPath(c, "app.openSearch.useServerless.enabled");
const oauthEnabled = (c: ConfigShape) =>
    !!getByPath(c, "app.authProvider.useExternalOAuthIdp.enabled");
const externalVpc = (c: ConfigShape) => {
    const v = getByPath(c, "app.useGlobalVpc.optionalExternalVpcId");
    return v != null && v !== "" && v !== "UNDEFINED";
};
const garnet = (c: ConfigShape) => !!getByPath(c, "app.addons.useGarnetFramework.enabled");
const physna = (c: ConfigShape) => !!getByPath(c, "app.addons.usePhysnaSync.enabled");

/**
 * Factory for a GPU model sub-tree (Cosmos / Gr00t). Each model has enabled,
 * autoRegisterWithVAMS, instanceTypes, maxVCpus, and optionally an
 * autoTrigger string. All advanced, in the GPU pipelines section.
 */
function makeModelFields(
    basePath: string,
    label: string,
    opts: { hasAutoTrigger: boolean }
): FieldMeta[] {
    const fields: FieldMeta[] = [
        {
            path: `${basePath}.enabled`,
            label: `${label} — enabled`,
            input: "boolean",
            section: "pipelines-gpu",
            advanced: true,
        },
        {
            path: `${basePath}.autoRegisterWithVAMS`,
            label: `${label} — auto-register with VAMS`,
            input: "boolean",
            section: "pipelines-gpu",
            advanced: true,
        },
        {
            path: `${basePath}.instanceTypes`,
            label: `${label} — instance types`,
            input: "string-array",
            section: "pipelines-gpu",
            advanced: true,
            help: "Must be non-empty when this model is enabled (BEST_FIT_PROGRESSIVE order).",
        },
        {
            path: `${basePath}.maxVCpus`,
            label: `${label} — max vCPUs`,
            input: "number",
            section: "pipelines-gpu",
            advanced: true,
            min: 1,
        },
    ];
    if (opts.hasAutoTrigger) {
        fields.splice(2, 0, {
            path: `${basePath}.autoTriggerOnFileExtensionsUpload`,
            label: `${label} — auto-trigger file extensions`,
            input: "text",
            section: "pipelines-gpu",
            advanced: true,
            placeholder: ".mp4,.mov,.jpg",
            help: "Comma-separated extensions; leave empty to disable auto-trigger.",
        });
    }
    return fields;
}

const COSMOS = "app.pipelines.useNvidiaCosmos";
const GR00T = "app.pipelines.useNvidiaGr00t";

const cosmosModelFields: FieldMeta[] = [
    ...makeModelFields(`${COSMOS}.modelsPredict.text2world2B_v2`, "Cosmos Text2World 2B", {
        hasAutoTrigger: false,
    }),
    ...makeModelFields(`${COSMOS}.modelsPredict.video2world2B_v2`, "Cosmos Video2World 2B", {
        hasAutoTrigger: true,
    }),
    ...makeModelFields(`${COSMOS}.modelsPredict.text2world14B_v2`, "Cosmos Text2World 14B", {
        hasAutoTrigger: false,
    }),
    ...makeModelFields(`${COSMOS}.modelsPredict.video2world14B_v2`, "Cosmos Video2World 14B", {
        hasAutoTrigger: true,
    }),
    ...makeModelFields(`${COSMOS}.modelsTransfer.transfer2B`, "Cosmos Transfer 2B", {
        hasAutoTrigger: true,
    }),
    ...makeModelFields(`${COSMOS}.modelsReason.reason2B`, "Cosmos Reason 2B", {
        hasAutoTrigger: true,
    }),
    ...makeModelFields(`${COSMOS}.modelsReason.reason8B`, "Cosmos Reason 8B", {
        hasAutoTrigger: true,
    }),
];

export const FIELDS: FieldMeta[] = [
    // ===== Deployment basics =====
    {
        path: "name",
        label: "Application name",
        input: "text",
        section: "essentials",
        help: "Base application name used in the full CDK stack name.",
    },
    {
        path: "app.baseStackName",
        label: "Base stack name",
        input: "text",
        section: "essentials",
        help: "Stack environment name appended to resource names (e.g. prod).",
    },
    {
        path: "app.adminEmailAddress",
        label: "Admin email address",
        input: "text",
        section: "essentials",
        placeholder: "admin@example.com",
        help: "Initial super-admin email. A temporary password is sent here on first deploy. Required.",
    },
    {
        path: "app.adminUserId",
        label: "Admin user ID",
        input: "text",
        section: "essentials",
        help: "Username for the initial super-admin (can be an email). Required.",
    },
    {
        path: "env.account",
        label: "AWS account ID",
        input: "text",
        section: "essentials",
        placeholder: "123456789012",
        help: "Target AWS account for deployment. Recommended to set explicitly. If left blank, it resolves from the CDK_DEFAULT_ACCOUNT environment variable at deploy time.",
    },
    {
        path: "env.region",
        label: "AWS region",
        input: "text",
        section: "essentials",
        placeholder: "us-east-1",
        help: "Leave blank to resolve from CDK context / environment at deploy time.",
    },
    {
        path: "app.assetBuckets.createNewBucket",
        label: "Create a new asset bucket",
        input: "boolean",
        section: "essentials",
        help: "When off, you must register at least one external asset bucket.",
    },
    {
        path: "app.assetBuckets.defaultNewBucketSyncDatabaseId",
        label: "Default sync database ID",
        input: "text",
        section: "essentials",
        help: "Database to sync with the new bucket. Required when creating a new bucket.",
        visibleWhen: (c) => !!getByPath(c, "app.assetBuckets.createNewBucket"),
    },
    {
        path: "app.assetBuckets.externalAssetBuckets",
        label: "External asset buckets",
        input: "external-buckets",
        section: "essentials",
        advanced: true,
        help: "Register existing S3 buckets with VAMS. Required when not creating a new bucket.",
    },
    {
        path: "app.assetBuckets.presignedUrlNetworkRestrictions",
        label: "Presigned URL network restrictions",
        input: "presigned-url-restrictions",
        section: "essentials",
        advanced: true,
        help: "Restrict presigned URLs on the VAMS-created and auxiliary buckets to IP ranges or VPC endpoint IDs. The two lists are mutually exclusive; empty allows all.",
    },
    {
        path: "env.loadContextIgnoreVPCStacks",
        label: "Load context (ignore VPC stacks)",
        input: "boolean",
        section: "essentials",
        advanced: true,
        help: "Skip VPC-dependent stacks during the first phase of an external VPC import.",
    },

    // ===== Security & compliance =====
    {
        path: "app.useWaf",
        label: "Enable AWS WAF",
        input: "boolean",
        section: "security",
        help: "Web Application Firewall for CloudFront/ALB and API Gateway. Disabling generates a warning.",
    },
    {
        path: "app.useFips",
        label: "Use FIPS endpoints",
        input: "boolean",
        section: "security",
        help: "Also requires the AWS_USE_FIPS_ENDPOINT=true environment variable at deploy time.",
    },
    {
        path: "app.addStackCloudTrailLogs",
        label: "Add stack CloudTrail logs",
        input: "boolean",
        section: "security",
        advanced: true,
        help: "Create a dedicated CloudWatch Logs group and CloudTrail trail for this stack.",
    },
    {
        path: "app.useKmsCmkEncryption.enabled",
        label: "Customer-managed KMS encryption",
        input: "boolean",
        section: "security",
        help: "Apply a customer-managed KMS key to S3, DynamoDB, SQS, SNS, and OpenSearch.",
    },
    {
        path: "app.useKmsCmkEncryption.optionalExternalCmkArn",
        label: "External KMS key ARN (optional)",
        input: "text",
        section: "security",
        advanced: true,
        help: "Import an existing CMK instead of generating one. Must be in the deployment region.",
        visibleWhen: (c) => !!getByPath(c, "app.useKmsCmkEncryption.enabled"),
    },
    {
        path: "app.govCloud.enabled",
        label: "GovCloud mode",
        input: "boolean",
        section: "security",
        help: "Enforces VPC on, CloudFront off, and Location Service off. Also set for EU Sovereign Cloud deployments.",
    },
    {
        path: "app.govCloud.il6Compliant",
        label: "IL6 compliant",
        input: "boolean",
        section: "security",
        advanced: true,
        help: "Additionally forces Cognito off, WAF off, and KMS CMK on.",
        visibleWhen: (c) => !!getByPath(c, "app.govCloud.enabled"),
    },
    {
        path: "app.iamRoleConfig.useCustomBootstrapRoles",
        label: "Use custom bootstrap roles",
        input: "boolean",
        section: "security",
        advanced: true,
        help: "Advanced. Use custom CDK bootstrap role mappings from config/policy/iamRoleConfig.json.",
    },
    {
        path: "app.iamRoleConfig.useCustomVamsStackRoles",
        label: "Use custom VAMS stack roles",
        input: "boolean",
        section: "security",
        advanced: true,
        help: "Advanced. Use custom VAMS stack IAM role mappings from config/policy/iamRoleConfig.json.",
    },

    // ===== Networking (VPC) =====
    {
        path: "app.useGlobalVpc.enabled",
        label: "Enable global VPC",
        input: "boolean",
        section: "networking",
        help: "Auto-enabled when ALB, provisioned OpenSearch, or any container pipeline is on.",
    },
    {
        path: "app.useGlobalVpc.vpcCidrRange",
        label: "VPC CIDR range",
        input: "text",
        section: "networking",
        placeholder: "10.1.0.0/16",
        help: "CIDR for the VAMS-created VPC. Ignored when importing an external VPC.",
        visibleWhen: (c) => !!getByPath(c, "app.useGlobalVpc.enabled"),
    },
    {
        path: "app.useGlobalVpc.useForAllLambdas",
        label: "Use VPC for all Lambdas",
        input: "boolean",
        section: "networking",
        advanced: true,
        help: "Deploy all Lambda functions inside the VPC (FedRAMP / VPC-only requirements).",
        visibleWhen: (c) => !!getByPath(c, "app.useGlobalVpc.enabled"),
    },
    {
        path: "app.useGlobalVpc.addVpcEndpoints",
        label: "Add VPC endpoints",
        input: "boolean",
        section: "networking",
        advanced: true,
        help: "Create all required VPC endpoints. Disable only if your imported VPC already has them.",
        visibleWhen: (c) => !!getByPath(c, "app.useGlobalVpc.enabled"),
    },
    {
        path: "app.useGlobalVpc.optionalExternalVpcId",
        label: "External VPC ID (import)",
        input: "text",
        section: "networking",
        advanced: true,
        placeholder: "vpc-0123456789abcdef0",
        help: "Import an existing VPC. Requires isolated subnet IDs below.",
        visibleWhen: (c) => !!getByPath(c, "app.useGlobalVpc.enabled"),
    },
    {
        path: "app.useGlobalVpc.optionalExternalIsolatedSubnetIds",
        label: "External isolated subnet IDs",
        input: "text",
        section: "networking",
        advanced: true,
        placeholder: "subnet-aaa,subnet-bbb",
        help: "Comma-delimited. Required when importing an external VPC.",
        visibleWhen: (c) => getByPath(c, "app.useGlobalVpc.enabled") && externalVpc(c),
    },
    {
        path: "app.useGlobalVpc.optionalExternalPrivateSubnetIds",
        label: "External private subnet IDs",
        input: "text",
        section: "networking",
        advanced: true,
        placeholder: "subnet-ccc,subnet-ddd",
        help: "Required for RapidPipeline/ModelOps with an imported VPC.",
        visibleWhen: (c) => getByPath(c, "app.useGlobalVpc.enabled") && externalVpc(c),
    },
    {
        path: "app.useGlobalVpc.optionalExternalPublicSubnetIds",
        label: "External public subnet IDs",
        input: "text",
        section: "networking",
        advanced: true,
        placeholder: "subnet-eee,subnet-fff",
        help: "Required for public ALB or RapidPipeline/ModelOps with an imported VPC.",
        visibleWhen: (c) => getByPath(c, "app.useGlobalVpc.enabled") && externalVpc(c),
    },

    // ===== Web distribution =====
    {
        path: "app.useCloudFront.enabled",
        label: "Enable CloudFront",
        input: "boolean",
        section: "frontend",
        help: "Not available in GovCloud or EU Sovereign Cloud. Cannot be enabled together with ALB.",
    },
    {
        path: "app.useCloudFront.customDomain.enabled",
        label: "CloudFront custom domain",
        input: "boolean",
        section: "frontend",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.useCloudFront.enabled"),
    },
    {
        path: "app.useCloudFront.customDomain.domainHost",
        label: "CloudFront domain host",
        input: "text",
        section: "frontend",
        advanced: true,
        placeholder: "vams.example.com",
        visibleWhen: (c) => getByPath(c, "app.useCloudFront.enabled") && cfCustomDomain(c),
    },
    {
        path: "app.useCloudFront.customDomain.certificateArn",
        label: "CloudFront certificate ARN (us-east-1)",
        input: "text",
        section: "frontend",
        advanced: true,
        help: "ACM certificate ARN — must be in us-east-1 regardless of deployment region.",
        visibleWhen: (c) => getByPath(c, "app.useCloudFront.enabled") && cfCustomDomain(c),
    },
    {
        path: "app.useCloudFront.customDomain.optionalHostedZoneId",
        label: "CloudFront hosted zone ID (optional)",
        input: "text",
        section: "frontend",
        advanced: true,
        visibleWhen: (c) => getByPath(c, "app.useCloudFront.enabled") && cfCustomDomain(c),
    },
    {
        path: "app.useAlb.enabled",
        label: "Enable ALB",
        input: "boolean",
        section: "frontend",
        help: "Required for GovCloud and EU Sovereign Cloud. Cannot be enabled together with CloudFront.",
    },
    {
        path: "app.useAlb.domainHost",
        label: "ALB domain host",
        input: "text",
        section: "frontend",
        placeholder: "vams.example.com",
        help: "Required when ALB is enabled.",
        visibleWhen: albEnabled,
    },
    {
        path: "app.useAlb.certificateArn",
        label: "ALB certificate ARN",
        input: "text",
        section: "frontend",
        help: "ACM certificate ARN in the deployment region. Required when ALB is enabled.",
        visibleWhen: albEnabled,
    },
    {
        path: "app.useAlb.usePublicSubnet",
        label: "ALB in public subnets",
        input: "boolean",
        section: "frontend",
        advanced: true,
        help: "Warning: exposes the web application to the public internet.",
        visibleWhen: albEnabled,
    },
    {
        path: "app.useAlb.addAlbS3SpecialVpcEndpoint",
        label: "Add ALB S3 VPC endpoint",
        input: "boolean",
        section: "frontend",
        advanced: true,
        help: "Creates the S3 VPC interface endpoint the ALB needs to serve static files.",
        visibleWhen: albEnabled,
    },
    {
        path: "app.useAlb.optionalHostedZoneId",
        label: "ALB hosted zone ID (optional)",
        input: "text",
        section: "frontend",
        advanced: true,
        help: "Route 53 hosted zone ID for automatic DNS alias creation.",
        visibleWhen: albEnabled,
    },

    // ===== Search =====
    {
        path: "app.openSearch.useServerless.enabled",
        label: "OpenSearch Serverless",
        input: "boolean",
        section: "search",
        help: "Pay-per-use search. Cannot be combined with Provisioned.",
    },
    {
        path: "app.openSearch.useServerless.nextGen",
        label: "Serverless — next-gen generation",
        input: "boolean",
        section: "search",
        advanced: true,
        help: "NEXTGEN generation (scale-to-zero capable). Must be false for GovCloud and EU Sovereign Cloud.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.allowPublic",
        label: "Serverless — allow public access",
        input: "boolean",
        section: "search",
        advanced: true,
        help: "When false, the collection is reachable only through a VPC endpoint (requires VPC). Set false for production.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.enableStandbyReplicas",
        label: "Serverless — standby replicas",
        input: "boolean",
        section: "search",
        advanced: true,
        help: "Required (true) for the NEXTGEN generation; optional for CLASSIC.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.minIndexingOcu",
        label: "Serverless — min indexing OCU",
        input: "number",
        section: "search",
        advanced: true,
        min: 0,
        help: "One of 0, 2, 4, 8, 16, or a multiple of 16. 0 (scale-to-zero) requires next-gen.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.maxIndexingOcu",
        label: "Serverless — max indexing OCU",
        input: "number",
        section: "search",
        advanced: true,
        min: 2,
        help: "One of 2, 4, 8, 16, or a multiple of 16 (and at least min indexing OCU).",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.minSearchOcu",
        label: "Serverless — min search OCU",
        input: "number",
        section: "search",
        advanced: true,
        min: 0,
        help: "One of 0, 2, 4, 8, 16, or a multiple of 16. 0 (scale-to-zero) requires next-gen.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.maxSearchOcu",
        label: "Serverless — max search OCU",
        input: "number",
        section: "search",
        advanced: true,
        min: 2,
        help: "One of 2, 4, 8, 16, or a multiple of 16 (and at least min search OCU).",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useServerless.deployDeferredIndexSchema",
        label: "Serverless — deploy deferred index schema",
        input: "boolean",
        section: "search",
        advanced: true,
        help: "Set true for one deployment to finish a deferred private next-gen setup, then set back to false.",
        visibleWhen: serverless,
    },
    {
        path: "app.openSearch.useProvisioned.enabled",
        label: "OpenSearch Provisioned",
        input: "boolean",
        section: "search",
        help: "Provisioned domain. Requires a VPC with at least availabilityZoneCount Availability Zones.",
    },
    {
        path: "app.openSearch.useProvisioned.availabilityZoneCount",
        label: "Availability zone count",
        input: "number",
        section: "search",
        advanced: true,
        min: 2,
        help: "Must be 2 or 3. At 3 the domain runs Multi-AZ with Standby. EU Sovereign Cloud (eusc-de-east-1) supports at most 2.",
        visibleWhen: provisioned,
    },
    {
        path: "app.openSearch.useProvisioned.numberOfShards",
        label: "Number of primary shards",
        input: "number",
        section: "search",
        advanced: true,
        min: 1,
        help: "Primary shards per index. Increase for indexes expected to exceed ~60 GB.",
        visibleWhen: provisioned,
    },
    {
        path: "app.openSearch.useProvisioned.dataNodeInstanceType",
        label: "Data node instance type",
        input: "text",
        section: "search",
        advanced: true,
        visibleWhen: provisioned,
    },
    {
        path: "app.openSearch.useProvisioned.masterNodeInstanceType",
        label: "Master node instance type",
        input: "text",
        section: "search",
        advanced: true,
        visibleWhen: provisioned,
    },
    {
        path: "app.openSearch.useProvisioned.ebsInstanceNodeSizeGb",
        label: "EBS size per data node (GB)",
        input: "number",
        section: "search",
        advanced: true,
        min: 1,
        visibleWhen: provisioned,
    },
    {
        path: "app.openSearch.reindexOnCdkDeploy",
        label: "Reindex on CDK deploy",
        input: "boolean",
        section: "search",
        advanced: true,
        help: "Enable only for a second deploy after initial deploy/upgrade, then set back to false.",
    },
    {
        path: "app.useLocationService.enabled",
        label: "Amazon Location Service",
        input: "boolean",
        section: "search",
        help: "Map visualization of geo metadata. Not available in GovCloud or EU Sovereign Cloud. Requires OpenSearch.",
    },

    // ===== Authentication =====
    {
        path: "app.authProvider.useCognito.enabled",
        label: "Amazon Cognito",
        input: "boolean",
        section: "auth",
        help: "Cognito user pools. Cannot be combined with external OAuth.",
    },
    {
        path: "app.authProvider.useCognito.useSaml",
        label: "Cognito SAML federation",
        input: "boolean",
        section: "auth",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.authProvider.useCognito.enabled"),
    },
    {
        path: "app.authProvider.useCognito.useUserPasswordAuthFlow",
        label: "USER_PASSWORD_AUTH flow",
        input: "boolean",
        section: "auth",
        advanced: true,
        help: "Non-SRP flow. Generates a security warning — use only for system integrations.",
        visibleWhen: (c) => !!getByPath(c, "app.authProvider.useCognito.enabled"),
    },
    {
        path: "app.authProvider.useCognito.credTokenTimeoutSeconds",
        label: "Cognito token timeout (seconds)",
        input: "number",
        section: "auth",
        advanced: true,
        min: 1,
        visibleWhen: (c) => !!getByPath(c, "app.authProvider.useCognito.enabled"),
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.enabled",
        label: "External OAuth IdP",
        input: "boolean",
        section: "auth",
        help: "External OAuth 2.0 / OIDC provider. All fields below are required when enabled.",
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderUrl",
        label: "IdP provider URL",
        input: "text",
        section: "auth",
        advanced: true,
        placeholder: "https://idp.example.com",
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthClientId",
        label: "IdP client ID",
        input: "text",
        section: "auth",
        advanced: true,
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderScope",
        label: "IdP scope",
        input: "text",
        section: "auth",
        advanced: true,
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderScopeMfa",
        label: "IdP MFA scope",
        input: "text",
        section: "auth",
        advanced: true,
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthPrincipalDomain",
        label: "IdP principal domain",
        input: "text",
        section: "auth",
        advanced: true,
        placeholder: "idp.example.com",
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderTokenEndpoint",
        label: "IdP token endpoint",
        input: "text",
        section: "auth",
        advanced: true,
        placeholder: "/as/token.oauth2",
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderAuthorizationEndpoint",
        label: "IdP authorization endpoint",
        input: "text",
        section: "auth",
        advanced: true,
        placeholder: "/as/authorization.oauth2",
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.idpAuthProviderDiscoveryEndpoint",
        label: "IdP discovery endpoint",
        input: "text",
        section: "auth",
        advanced: true,
        placeholder: "/.well-known/openid-configuration",
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.lambdaAuthorizorJWTIssuerUrl",
        label: "Lambda authorizer JWT issuer URL",
        input: "text",
        section: "auth",
        advanced: true,
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.useExternalOAuthIdp.lambdaAuthorizorJWTAudience",
        label: "Lambda authorizer JWT audience",
        input: "text",
        section: "auth",
        advanced: true,
        visibleWhen: oauthEnabled,
    },
    {
        path: "app.authProvider.presignedUrlTimeoutSeconds",
        label: "Presigned URL timeout (seconds)",
        input: "number",
        section: "auth",
        advanced: true,
        min: 1,
        help: "TTL for S3 presigned upload/download URLs (default 86400 = 24h).",
    },
    {
        path: "app.authProvider.authorizerOptions.allowedIpRanges",
        label: "Allowed IP ranges",
        input: "ip-range-list",
        section: "auth",
        advanced: true,
        help: "Restrict API access to IP ranges. Each is a [min, max] IPv4 pair. Empty allows all.",
    },

    // ===== Pipelines — standard =====
    {
        path: "app.pipelines.useConversion3dBasic.enabled",
        label: "3D basic conversion",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        help: "Convert between STL, OBJ, PLY, GLTF, GLB, etc. No VPC required.",
    },
    {
        path: "app.pipelines.useConversion3dBasic.autoRegisterWithVAMS",
        label: "3D basic conversion — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useConversion3dBasic.enabled"),
    },
    {
        path: "app.pipelines.useConversionCadMeshMetadataExtraction.enabled",
        label: "CAD/mesh metadata extraction",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
    },
    {
        path: "app.pipelines.useConversionCadMeshMetadataExtraction.autoRegisterWithVAMS",
        label: "CAD/mesh extraction — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) =>
            !!getByPath(c, "app.pipelines.useConversionCadMeshMetadataExtraction.enabled"),
    },
    {
        path: "app.pipelines.useConversionCadMeshMetadataExtraction.autoRegisterAutoTriggerOnFileUpload",
        label: "CAD/mesh extraction — auto-trigger on upload",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) =>
            !!getByPath(c, "app.pipelines.useConversionCadMeshMetadataExtraction.enabled"),
    },
    {
        path: "app.pipelines.useConversionCoordinateTransform.enabled",
        label: "Coordinate transform conversion",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        help: "Transform 3D asset coordinate systems. Requires VPC.",
    },
    {
        path: "app.pipelines.useConversionCoordinateTransform.useCodeBuild",
        label: "Coordinate transform — build via CodeBuild",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) =>
            !!getByPath(c, "app.pipelines.useConversionCoordinateTransform.enabled"),
    },
    {
        path: "app.pipelines.useConversionCoordinateTransform.autoRegisterWithVAMS",
        label: "Coordinate transform — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) =>
            !!getByPath(c, "app.pipelines.useConversionCoordinateTransform.enabled"),
    },
    {
        path: "app.pipelines.useConversionCoordinateTransform.autoRegisterAutoTriggerOnFileUpload",
        label: "Coordinate transform — auto-trigger on upload",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) =>
            !!getByPath(c, "app.pipelines.useConversionCoordinateTransform.enabled"),
    },
    {
        path: "app.pipelines.usePreview3dThumbnail.enabled",
        label: "3D preview thumbnail",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        help: "GIF/PNG previews from 3D/CAD/point-cloud/USD files. Requires VPC.",
    },
    {
        path: "app.pipelines.usePreview3dThumbnail.autoRegisterWithVAMS",
        label: "3D thumbnail — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.usePreview3dThumbnail.enabled"),
    },
    {
        path: "app.pipelines.usePreview3dThumbnail.autoRegisterAutoTriggerOnFileUpload",
        label: "3D thumbnail — auto-trigger on upload",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.usePreview3dThumbnail.enabled"),
    },
    {
        path: "app.pipelines.usePreviewPcPotreeViewer.enabled",
        label: "Point cloud Potree viewer",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        help: "Process E57/LAS/LAZ for Potree web viewing. Requires VPC. GPL-licensed library.",
    },
    {
        path: "app.pipelines.usePreviewPcPotreeViewer.autoRegisterWithVAMS",
        label: "Potree viewer — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.usePreviewPcPotreeViewer.enabled"),
    },
    {
        path: "app.pipelines.usePreviewPcPotreeViewer.autoRegisterAutoTriggerOnFileUpload",
        label: "Potree viewer — auto-trigger on upload",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.usePreviewPcPotreeViewer.enabled"),
    },
    {
        path: "app.pipelines.usePreviewPcPotreeViewer.sqsAutoRunOnAssetModified",
        label: "Potree viewer — run on asset modified (SQS)",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.usePreviewPcPotreeViewer.enabled"),
    },
    {
        path: "app.pipelines.useGenAiMetadata3dLabeling.enabled",
        label: "GenAI metadata labeling",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        help: "Use Amazon Bedrock to label GLB/FBX/OBJ files. Requires VPC.",
    },
    {
        path: "app.pipelines.useGenAiMetadata3dLabeling.bedrockModelId",
        label: "GenAI — Bedrock model ID",
        input: "text",
        section: "pipelines-standard",
        advanced: true,
        help: "Required when enabled (e.g. global.anthropic.claude-sonnet-4-5-20250929-v1:0).",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useGenAiMetadata3dLabeling.enabled"),
    },
    {
        path: "app.pipelines.useGenAiMetadata3dLabeling.autoRegisterWithVAMS",
        label: "GenAI — auto-register",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useGenAiMetadata3dLabeling.enabled"),
    },
    {
        path: "app.pipelines.useGenAiMetadata3dLabeling.autoRegisterAutoTriggerOnFileUpload",
        label: "GenAI — auto-trigger on upload",
        input: "boolean",
        section: "pipelines-standard",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useGenAiMetadata3dLabeling.enabled"),
    },

    // ===== Pipelines — GPU / third-party =====
    {
        path: "app.pipelines.useSplatToolbox.enabled",
        label: "Gaussian splatting",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Generate Gaussian splat reconstructions from media. Requires VPC + GPU.",
    },
    {
        path: "app.pipelines.useSplatToolbox.autoRegisterWithVAMS",
        label: "Gaussian splatting — auto-register",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useSplatToolbox.enabled"),
    },
    {
        path: "app.pipelines.useSplatToolbox.sqsAutoRunOnAssetModified",
        label: "Gaussian splatting — run on asset modified (SQS)",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useSplatToolbox.enabled"),
    },
    {
        path: "app.pipelines.useIsaacLabTraining.enabled",
        label: "Isaac Lab training",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "NVIDIA Isaac Lab RL training on GPU. Requires VPC and NVIDIA EULA acceptance.",
    },
    {
        path: "app.pipelines.useIsaacLabTraining.acceptNvidiaEula",
        label: "Isaac Lab — accept NVIDIA EULA",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when Isaac Lab is enabled.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useIsaacLabTraining.enabled"),
    },
    {
        path: "app.pipelines.useIsaacLabTraining.useCodeBuild",
        label: "Isaac Lab — build via CodeBuild",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Build the Isaac Lab container in the cloud with AWS CodeBuild instead of locally during CDK deploy.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useIsaacLabTraining.enabled"),
    },
    {
        path: "app.pipelines.useIsaacLabTraining.autoRegisterWithVAMS",
        label: "Isaac Lab — auto-register",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useIsaacLabTraining.enabled"),
    },
    {
        path: "app.pipelines.useIsaacLabTraining.keepWarmInstance",
        label: "Isaac Lab — keep warm instance",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Warning: incurs continuous compute cost even when idle.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useIsaacLabTraining.enabled"),
    },
    // RapidPipeline ECS
    {
        path: "app.pipelines.useRapidPipeline.useEcs.enabled",
        label: "RapidPipeline (ECS)",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Third-party optimization on ECS. Requires VPC and a Marketplace subscription.",
    },
    {
        path: "app.pipelines.useRapidPipeline.useEcs.ecrContainerImageURI",
        label: "RapidPipeline ECS — ECR image URI",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when enabled.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEcs.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEcs.autoRegisterWithVAMS",
        label: "RapidPipeline ECS — auto-register",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEcs.enabled"),
    },
    // RapidPipeline EKS
    {
        path: "app.pipelines.useRapidPipeline.useEks.enabled",
        label: "RapidPipeline (EKS)",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Third-party optimization on EKS. Requires VPC (2+ AZs) and a Marketplace subscription.",
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.ecrContainerImageURI",
        label: "RapidPipeline EKS — ECR image URI",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when enabled.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.autoRegisterWithVAMS",
        label: "RapidPipeline EKS — auto-register",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.eksClusterVersion",
        label: "EKS cluster version",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.nodeInstanceType",
        label: "EKS node instance type",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.minNodes",
        label: "EKS min nodes",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.maxNodes",
        label: "EKS max nodes",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 1,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.desiredNodes",
        label: "EKS desired nodes",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.jobTimeout",
        label: "EKS job timeout (seconds)",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 1,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.jobMemory",
        label: "EKS job memory",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.jobCpu",
        label: "EKS job CPU",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.jobBackoffLimit",
        label: "EKS job backoff limit",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.jobTTLSecondsAfterFinished",
        label: "EKS job TTL after finished (seconds)",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.observability.enableControlPlaneLogs",
        label: "EKS — control plane logs",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    {
        path: "app.pipelines.useRapidPipeline.useEks.observability.enableContainerInsights",
        label: "EKS — container insights",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useRapidPipeline.useEks.enabled"),
    },
    // ModelOps
    {
        path: "app.pipelines.useModelOps.enabled",
        label: "ModelOps (VNTANA)",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Third-party 3D optimization on AWS Batch. Requires VPC and a Marketplace subscription.",
    },
    {
        path: "app.pipelines.useModelOps.ecrContainerImageURI",
        label: "ModelOps — ECR image URI",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when enabled.",
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useModelOps.enabled"),
    },
    {
        path: "app.pipelines.useModelOps.autoRegisterWithVAMS",
        label: "ModelOps — auto-register",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, "app.pipelines.useModelOps.enabled"),
    },
    // NVIDIA Cosmos shared settings + models
    {
        path: `${COSMOS}.enabled`,
        label: "NVIDIA Cosmos",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "World foundation models (Predict/Reason/Transfer). Requires VPC + GPU + internet.",
    },
    {
        path: `${COSMOS}.huggingFaceToken`,
        label: "Cosmos — HuggingFace token",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when Cosmos is enabled. Stored in Secrets Manager at deploy.",
        visibleWhen: (c) => !!getByPath(c, `${COSMOS}.enabled`),
    },
    {
        path: `${COSMOS}.useCodeBuild`,
        label: "Cosmos — build via CodeBuild",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, `${COSMOS}.enabled`),
    },
    {
        path: `${COSMOS}.useWarmInstances`,
        label: "Cosmos — keep warm instances",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "Warning: continuous GPU cost (~$5.67/hr per g5.12xlarge).",
        visibleWhen: (c) => !!getByPath(c, `${COSMOS}.enabled`),
    },
    {
        path: `${COSMOS}.warmInstanceCount`,
        label: "Cosmos — warm instance count",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, `${COSMOS}.enabled`),
    },
    ...cosmosModelFields.map((f) => ({
        ...f,
        visibleWhen: (c: ConfigShape) => !!getByPath(c, `${COSMOS}.enabled`),
    })),
    // NVIDIA Gr00t shared settings + model
    {
        path: `${GR00T}.enabled`,
        label: "NVIDIA Gr00t fine-tuning",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        help: "GR00T-N1.5-3B fine-tuning for embodied AI. Requires VPC + GPU + internet.",
    },
    {
        path: `${GR00T}.huggingFaceToken`,
        label: "Gr00t — HuggingFace token",
        input: "text",
        section: "pipelines-gpu",
        advanced: true,
        help: "Required when Gr00t is enabled. Must have access to nvidia/GR00T-N1.5-3B.",
        visibleWhen: (c) => !!getByPath(c, `${GR00T}.enabled`),
    },
    {
        path: `${GR00T}.useCodeBuild`,
        label: "Gr00t — build via CodeBuild",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, `${GR00T}.enabled`),
    },
    {
        path: `${GR00T}.useWarmInstances`,
        label: "Gr00t — keep warm instances",
        input: "boolean",
        section: "pipelines-gpu",
        advanced: true,
        visibleWhen: (c) => !!getByPath(c, `${GR00T}.enabled`),
    },
    {
        path: `${GR00T}.warmInstanceCount`,
        label: "Gr00t — warm instance count",
        input: "number",
        section: "pipelines-gpu",
        advanced: true,
        min: 0,
        visibleWhen: (c) => !!getByPath(c, `${GR00T}.enabled`),
    },
    ...makeModelFields(`${GR00T}.modelsFinetune.gr00tN1_5_3B`, "Gr00t N1.5 3B", {
        hasAutoTrigger: false,
    }).map((f) => ({
        ...f,
        visibleWhen: (c: ConfigShape) => !!getByPath(c, `${GR00T}.enabled`),
    })),

    // ===== Add-ons (Garnet) =====
    {
        path: "app.addons.useGarnetFramework.enabled",
        label: "Garnet Framework",
        input: "boolean",
        section: "addons",
        advanced: true,
        help: "NGSI-LD knowledge-graph synchronization of VAMS data changes.",
    },
    {
        path: "app.addons.useGarnetFramework.garnetApiEndpoint",
        label: "Garnet API endpoint",
        input: "text",
        section: "addons",
        advanced: true,
        placeholder: "https://XXX.execute-api.us-east-1.amazonaws.com",
        help: "Required when Garnet is enabled. Must be a valid URL.",
        visibleWhen: garnet,
    },
    {
        path: "app.addons.useGarnetFramework.garnetApiToken",
        label: "Garnet API token",
        input: "text",
        section: "addons",
        advanced: true,
        help: "Required when Garnet is enabled.",
        visibleWhen: garnet,
    },
    {
        path: "app.addons.useGarnetFramework.garnetIngestionQueueSqsUrl",
        label: "Garnet ingestion SQS URL",
        input: "text",
        section: "addons",
        advanced: true,
        placeholder: "https://sqs.us-east-1.amazonaws.com/123456789012/queue-name",
        help: "Required when Garnet is enabled.",
        visibleWhen: garnet,
    },
    {
        path: "app.addons.usePhysnaSync.enabled",
        label: "Physna Sync",
        input: "boolean",
        section: "addons",
        advanced: true,
        help: "Sync VAMS 3D/CAD assets to Physna for geometric search.",
    },
    {
        path: "app.addons.usePhysnaSync.tenantId",
        label: "Physna — tenant ID",
        input: "text",
        section: "addons",
        advanced: true,
        help: "Required when Physna Sync is enabled.",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.apiBaseEndpoint",
        label: "Physna — API base endpoint",
        input: "text",
        section: "addons",
        advanced: true,
        placeholder: "https://app-api.physna.com/v3/",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.authTokenEndpoint",
        label: "Physna — auth token endpoint",
        input: "text",
        section: "addons",
        advanced: true,
        placeholder: "https://physna-app.auth.us-east-2.amazoncognito.com/oauth2/token",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.authType",
        label: "Physna — auth type",
        input: "text",
        section: "addons",
        advanced: true,
        placeholder: "cognito",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.clientId",
        label: "Physna — client ID",
        input: "text",
        section: "addons",
        advanced: true,
        help: "Cognito client ID. VAMS creates and populates the credentials secret at deploy time.",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.clientSecret",
        label: "Physna — client secret",
        input: "text",
        section: "addons",
        advanced: true,
        help: "Cognito client secret. VAMS populates the secret via a custom resource so the value is not written into the CloudFormation template.",
        visibleWhen: physna,
    },
    {
        path: "app.addons.usePhysnaSync.credentialsSecretArn",
        label: "Physna — credentials secret ARN (optional)",
        input: "text",
        section: "addons",
        advanced: true,
        help: "Optional: ARN of an operator-managed Secrets Manager secret ({clientId, clientSecret}). When set, client ID/secret above are ignored.",
        visibleWhen: physna,
    },

    // ===== API & Web UI =====
    {
        path: "app.api.apiType",
        label: "API type",
        input: "select",
        section: "api-webui",
        advanced: true,
        options: [{ value: "APIGATEWAY_REST", label: "API Gateway REST" }],
        help: "Backend API implementation type. Only APIGATEWAY_REST is supported.",
    },
    {
        path: "app.api.apiGatewayRest.globalRateLimit",
        label: "API global rate limit (req/s)",
        input: "number",
        section: "api-webui",
        advanced: true,
        min: 1,
    },
    {
        path: "app.api.apiGatewayRest.globalBurstLimit",
        label: "API global burst limit",
        input: "number",
        section: "api-webui",
        advanced: true,
        min: 1,
        help: "Must be greater than or equal to the rate limit.",
    },
    {
        path: "app.api.apiGatewayRest.endpointType",
        label: "API endpoint type",
        input: "select",
        section: "api-webui",
        advanced: true,
        options: [
            { value: "REGIONAL", label: "Regional (public)" },
            { value: "PRIVATE", label: "Private (VPC endpoint)" },
        ],
        help: "PRIVATE requires a VPC with an execute-api endpoint and must be fronted by an ALB (not CloudFront).",
    },
    {
        path: "app.api.apiGatewayRest.optionalExternalPrivateApigVPCEId",
        label: "External private API VPC endpoint ID",
        input: "text",
        section: "api-webui",
        advanced: true,
        placeholder: "vpce-0123456789abcdef0",
        help: "For a PRIVATE endpoint when VAMS does not create one (addVpcEndpoints = false). Ignored for REGIONAL.",
        visibleWhen: (c) => getByPath(c, "app.api.apiGatewayRest.endpointType") === "PRIVATE",
    },
    {
        path: "app.webUi.optionalBannerHtmlMessage",
        label: "Web UI banner HTML message",
        input: "text",
        section: "api-webui",
        advanced: true,
        help: "Optional banner shown in the web interface (system/compliance notices).",
    },
    {
        path: "app.webUi.allowUnsafeEvalFeatures",
        label: "Allow unsafe-eval (CSP)",
        input: "boolean",
        section: "api-webui",
        advanced: true,
        help: "Required for certain viewer plugins. Consult your security team before enabling.",
    },

    // ===== Metadata schema auto-load =====
    {
        path: "app.metadataSchema.autoLoadDefaultAssetLinksSchema",
        label: "Auto-load default asset-links schema",
        input: "boolean",
        section: "metadata",
        advanced: true,
    },
    {
        path: "app.metadataSchema.autoLoadDefaultDatabaseSchema",
        label: "Auto-load default database schema",
        input: "boolean",
        section: "metadata",
        advanced: true,
    },
    {
        path: "app.metadataSchema.autoLoadDefaultAssetSchema",
        label: "Auto-load default asset schema",
        input: "boolean",
        section: "metadata",
        advanced: true,
    },
    {
        path: "app.metadataSchema.autoLoadDefaultAssetFileSchema",
        label: "Auto-load default asset-file schema",
        input: "boolean",
        section: "metadata",
        advanced: true,
    },
];

/** Fields belonging to a section, in declaration order. */
export function fieldsForSection(sectionId: string): FieldMeta[] {
    return FIELDS.filter((f) => f.section === sectionId);
}
